Use 2 spaces

diff --git a/bin/do-pkgs b/bin/do-pkgs
--- a/bin/do-pkgs
+++ b/bin/do-pkgs
@@ -3,46 +3,46 @@
 set -eu
 
 panic() {
-    echo "$1" >&2
-    exit 1
+  echo "$1" >&2
+  exit 1
 }
 
 do_brew() {
-    brew update
-    brew bundle --verbose --global || true
-    brew bundle cleanup --force --global
-    brew unlink coreutils >/dev/null
-    brew cleanup
-    brew prune
+  brew update
+  brew bundle --verbose --global || true
+  brew bundle cleanup --force --global
+  brew unlink coreutils >/dev/null
+  brew cleanup
+  brew prune
 }
 
 do_npm() {
-    npm i -g npm
+  npm i -g npm
 }
 
 do_tlmgr() {
-    tlmgr update --self
-    tlmgr update --all
+  tlmgr update --self
+  tlmgr update --all
 }
 
 try() {
-    if ! command -v "$1" >/dev/null; then
-        echo "'$1' not found"
-        return
-    fi
-    echo "doing $1"
-    case "$1" in
-    (brew) do_brew ;;
-    (npm) do_npm ;;
-    (tlmgr) do_tlmgr ;;
-    (*) panic "unknown package manager '$1'" ;;
-    esac
+  if ! command -v "$1" >/dev/null; then
+    echo "'$1' not found"
+    return
+  fi
+  echo "doing $1"
+  case "$1" in
+  (brew) do_brew ;;
+  (npm) do_npm ;;
+  (tlmgr) do_tlmgr ;;
+  (*) panic "unknown package manager '$1'" ;;
+  esac
 }
 
 if [ "$#" -eq 0 ]; then
-    try brew
-    try npm
-    try tlmgr
+  try brew
+  try npm
+  try tlmgr
 else
-    try "$@"
+  try "$@"
 fi
