do not do-subl if no subl

diff --git a/bin/do-subl b/bin/do-subl
--- a/bin/do-subl
+++ b/bin/do-subl
@@ -1,11 +1,17 @@
 #!/bin/sh
 
 set -eu
+. "$HOME/.config/lib/cmd_found.sh"
 . "$HOME/.config/lib/panic.sh"
 . "$HOME/.config/lib/symlink.sh"
 
 if [ $# -ne 0 ]; then
 	panic "usage: $(basename "$0")"
+fi
+
+if ! cmd_found subl; then
+	echo "'subl' not found"
+	exit
 fi
 
 config_subl="$HOME/.config/sublime-text-3"
