do not use && and || shortcuts

diff --git a/bin/git-browse b/bin/git-browse
--- a/bin/git-browse
+++ b/bin/git-browse
@@ -6,9 +6,12 @@
 git rev-parse >/dev/null
 
 remote="origin"
-[ $# -ge 1 ] && remote="$1"
+if [ $# -ge 1 ]; then
+    remote="$1"
+fi
 
-url="$(git config remote.$remote.url)" \
-    || abort "could not get url for remote '$remote'"
+if ! url="$(git config remote.$remote.url)"; then
+    abort "could not get url for remote '$remote'"
+fi
 
 open "$url"
