fix some logic

diff --git a/bin/update-dotfiles b/bin/update-dotfiles
--- a/bin/update-dotfiles
+++ b/bin/update-dotfiles
@@ -22,11 +22,11 @@ if [ \
 	git fetch -q origin master
 fi
 
-if ! git merge-base --is-ancestor origin/master HEAD \
-&& git rebase -q origin/master; then
+if ! git merge-base --is-ancestor origin/master HEAD; then
+	if ! git rebase -q origin/master; then
+		abort "cd to '$HOME/.config' to resolve this error"
+	fi
 	"$HOME/.config/bin/do-home"
-else
-	abort "cd to '$HOME/.config' to resolve this error"
 fi
 
 git log -1 --format='%h%d %cr' origin/master
