*.sh: use && only when it makes sense

diff --git a/libexec/install b/libexec/install
--- a/libexec/install
+++ b/libexec/install
@@ -6,7 +6,8 @@ set -euo pipefail
 IFS=$'\n\t'
 
 abort() {
-    echo "\e[31merror:\e[0m $1" && exit 1
+    echo "\e[31merror:\e[0m $1"
+    exit 1
 }
 
 [[ "$USER" == "root" ]] && abort "do not run as root"
