fully use sh

diff --git a/libexec/install b/libexec/install
--- a/libexec/install
+++ b/libexec/install
@@ -1,4 +1,4 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env sh
 
 wrapper() {
 
@@ -6,7 +6,7 @@ set -euo pipefail
 IFS=$'\n\t'
 
 abort() {
-    echo "\e[31merror:\e[0m $1"
+    echo 1>&2 $'\e[31merror:\e[0m' "$1"
     exit 1
 }
 
